### PR TITLE
Settings - new launcher #97

### LINKED ISSUE #97: Settings - new launcher
#57  - settings screen implementation

### PR DESCRIPTION
**Pull request by AlbertoSamele**
# Description

Added Video, Controls and account settings screens.

Fixes #97

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation comments
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by stackotter** [comment]
It looks great so far! There are just a few things to fix.

The first thing is that the dropdown style looks a little funny (the first separator should be the full width i think):

Screen Shot 2022-03-28 at 12 17 15

## Video

The sliders are both continuous, whereas the render distance slider should be discrete (clicks to the closest integer).

The value of each slider should also be displayed next to the slider label. And the field of view slider should click to 90 degrees when within a few degrees, because that's a common value (the default). I think if you look at the original code for that slider you'll be able to see the logic that i used for that.

Also, the min and max labels of the sliders seem to be affecting the position and width of the slider. I think it would look neater if the sliders were a fixed width and the min/max labels are just offset outwards.

## Controls

When clicking a button in the controls menu to bind a key, the label and button seem to shift a few pixels to the right.

## Account

Rename the title to `Accounts` and rename the edit button to `add`, originally it was edit because it allowed reordering the list and everything, but if it's just for adding accounts it should be `add`.

## Code style

Just the usual, no empty line at the start/end of a struct, no double new lines.

## Conclusion

The overall styles look great and intuitive, there are just a few layout and usability issues mainly.

I can't see why the keymap editor isn't working, have you tried making it a button instead of a tap gesture temporarily to see if it makes any difference? That's the only change you made that seems relevant to the issue

**Comment by stackotter** [comment]
Oh, I also just realised that the dropdown should close when the user clicks outside of it

**Comment by ninjadev64** [comment]
@stackotter remember the default FOV is 70 not 90

**Comment by stackotter** [comment]
> @stackotter remember the default FOV is 70 not 90

Oh, really? Open an issue for that to be fixed so that I don't forget

**Comment by Matthew15625** [comment]
Hmm but doesn’t everyone increase the fov to around 90 anyway? I think it’s fine having the default as 90 on delta

**Comment by ninjadev64** [comment]
@stackotter I already told you about it once, look at your Snapshot 6 release

**Comment by stackotter** [comment]
Oh right yeah, I've fixed that, and 70 is currently still the default, why did you bring it up then?

**Comment by ninjadev64** [comment]
> Oh right yeah, I fixed that ages ago, and 70 is currently still the default, why did you bring it up then?

Because in your message to Alberto you said the fov slider should click to 90 degreees

> And the field of view slider should click to 90 degrees when within a few degrees, because that's a common value (the default).

**Comment by stackotter** [comment]
Oh right yeah my bad, I meant 70

**Comment by Bra-svg** [comment]
Hi , Welcome all thanks for Delta Client

**Comment by stackotter** [comment]
What?

**Pull request merged**
