### PR TITLE
Create a CustomJSONDecoder wrapper, and replace swift-concurrency with swift-atomics

### PR DESCRIPTION
**Pull request by ninjadev64**
# Description

This PR creates a CustomJSONDecoder struct, which wraps around the ZippyJSONDecoder and JSONDecoder `decode` method depending on platform. ZippyJSONDecoder is used on all platforms except Linux, where it is not currently supported.

Additionally, this PR replaces swift-concurrency with swift-atomics, which builds on Linux. Thanks to [LeoDog896](https://github.com/LeoDog896/delta-client/commit/63cbe2035330b2c2c2028e7b3d9878322cfa39c2) for originally making this change.

This should warrant an update to #113.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code where required, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation comments
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by InfRandomness** [comment]
Please solve these : 
- https://github.com/stackotter/delta-client/actions/runs/3080699453/jobs/4978356481#step:4:430
- https://github.com/stackotter/delta-client/actions/runs/3080699453/jobs/4978356481#step:4:592
- https://github.com/stackotter/delta-client/actions/runs/3080699453/jobs/4978356481#step:4:709

**Comment by InfRandomness** [comment]
It would also be nice to either make all of the commits build successfully
you can do that by either : rebasing and x commit into y commit
or do it by rewriting the history with interactive rebasing

**Comment by ninjadev64** [comment]
> Please solve these :
> 
> * https://github.com/stackotter/delta-client/actions/runs/3080699453/jobs/4978356481#step:4:430
> * https://github.com/stackotter/delta-client/actions/runs/3080699453/jobs/4978356481#step:4:592
> * https://github.com/stackotter/delta-client/actions/runs/3080699453/jobs/4978356481#step:4:709

These linter violations are not caused by my code.


> It would also be nice to either make all of the commits build successfully you can do that by either : rebasing and x commit into y commit or do it by rewriting the history with interactive rebasing

A little bit unnecessary, no?

**Comment by InfRandomness** [comment]
> > It would also be nice to either make all of the commits build successfully you can do that by either : rebasing and x commit into y commit or do it by rewriting the history with interactive rebasing
> 
> A little bit unnecessary, no?
Do you really want to merge an unclean history into main?????

**Comment by ninjadev64** [comment]
> > > It would also be nice to either make all of the commits build successfully you can do that by either : rebasing and x commit into y commit or do it by rewriting the history with interactive rebasing
> > 
> > 
> > A little bit unnecessary, no?
> 
> Do you really want to merge an unclean history into main?????

It's not like main has a 100% clean track record, but stackotter should squash this PR before merging anyway.

**Comment by InfRandomness** [comment]
> > > > It would also be nice to either make all of the commits build successfully you can do that by either : rebasing and x commit into y commit or do it by rewriting the history with interactive rebasing
> > > 
> > > 
> > > A little bit unnecessary, no?
> > 
> > 
> > Do you really want to merge an unclean history into main?????
> 
> It's not like main has a 100% clean track record, but stackotter should squash this PR before merging anyway.

this makes it all even worse, god damn
I give up

**Comment by stackotter** [comment]
@InfRandomness it is nice to have a clean commit history on main, I agree. However, I don't want to force contributors to rebase cause not everyone knows how to, so I usually just squash merge if the commits don't obviously need to be separate. Mostly PRs are pretty small so it's not sacrificing too much commit granularity.

**Review by stackotter — APPROVED** [review]
All looks good to me! I'll merge it once I'm at my laptop and I can just give it a quick run to check

**Pull request merged**
